### ISSUE TITLE
Hard coded /b/ in eve.py

### ISSUE THREAD

**Issue by ghost** [AGSPhoenix/eve#9]
https://github.com/AGSPhoenix/eve/blob/453a81636a7ad2194f971f0daa6328af9b4592aa/eve.py#L133

Will raise **_mysql_exceptions.ProgrammingError: (1146, "Table 'asagi.b' doesn't exist")**

**Comment by AGSPhoenix** [comment]
This is what happens when you only test on one board.

Fixed.
